//
//  RunLogTests.swift
//  WhiskyKitTests
//
//  This file is part of Whisky.
//
//  Whisky is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Whisky is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Whisky.
//  If not, see https://www.gnu.org/licenses/.
//

@testable import WhiskyKit
import XCTest

final class RunLogTests: XCTestCase {
    var tempDir: URL!

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory.appending(path: "runlog_\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    // MARK: - RunLogEntry Tests

    func testEntryCreationHasAutoGeneratedIdAndStartTime() {
        let entry = RunLogEntry(programName: "game.exe", logFileName: "2025-01-01T00:00:00Z.log")
        XCTAssertFalse(entry.id.uuidString.isEmpty)
        XCTAssertNotNil(entry.startTime)
        XCTAssertEqual(entry.programName, "game.exe")
        XCTAssertEqual(entry.logFileName, "2025-01-01T00:00:00Z.log")
    }

    func testIsRunningWhenNoEndTime() {
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        XCTAssertTrue(entry.isRunning)
        XCTAssertNil(entry.endTime)
        XCTAssertNil(entry.exitCode)
    }

    func testIsNotRunningWhenEndTimeSet() {
        var entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        entry.endTime = Date()
        entry.exitCode = 0
        XCTAssertFalse(entry.isRunning)
    }

    func testDurationIsNilWhileRunning() {
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        XCTAssertNil(entry.duration)
    }

    func testDurationIsCalculatedWhenComplete() throws {
        var entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        let start = entry.startTime
        entry.endTime = start.addingTimeInterval(120)
        let duration = try XCTUnwrap(entry.duration)
        XCTAssertEqual(duration, 120, accuracy: 0.001)
    }

    // MARK: - RunLogHistory Tests

    func testAppendAddsEntry() {
        var history = RunLogHistory()
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        let removed = history.append(entry)
        XCTAssertEqual(history.entries.count, 1)
        XCTAssertTrue(removed.isEmpty)
    }

    func testAppendPrunesAtMaxEntries() {
        var history = RunLogHistory()
        var allEntries: [RunLogEntry] = []

        // Add 12 entries (2 more than max of 10)
        for idx in 0 ..< 12 {
            let entry = RunLogEntry(programName: "game.exe", logFileName: "log_\(idx).log")
            allEntries.append(entry)
            let removed = history.append(entry)
            if idx >= RunLogHistory.maxEntriesPerProgram {
                XCTAssertFalse(removed.isEmpty, "Should have pruned at entry \(idx)")
            }
        }

        XCTAssertEqual(history.entries.count, RunLogHistory.maxEntriesPerProgram)
        // Oldest entries should have been removed
        XCTAssertEqual(history.entries.first?.id, allEntries[2].id)
        XCTAssertEqual(history.entries.last?.id, allEntries[11].id)
    }

    func testMarkCompletedUpdatesEndTimeAndExitCode() {
        var history = RunLogHistory()
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        let entryId = entry.id
        history.append(entry)

        history.markCompleted(id: entryId, exitCode: 0, hasWineDebug: false)

        let updated = history.entries.first { $0.id == entryId }
        XCTAssertNotNil(updated?.endTime)
        XCTAssertEqual(updated?.exitCode, 0)
        XCTAssertFalse(updated?.isRunning ?? true)
        XCTAssertEqual(updated?.hasWineDebugOutput, false)
    }

    func testMarkCompletedWithWineDebugFlag() {
        var history = RunLogHistory()
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        let entryId = entry.id
        history.append(entry)

        history.markCompleted(id: entryId, exitCode: 1, hasWineDebug: true)

        let updated = history.entries.first { $0.id == entryId }
        XCTAssertEqual(updated?.exitCode, 1)
        XCTAssertEqual(updated?.hasWineDebugOutput, true)
    }

    func testMarkCompletedWithNonexistentIdIsNoOp() {
        var history = RunLogHistory()
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        history.append(entry)

        history.markCompleted(id: UUID(), exitCode: 42, hasWineDebug: false)

        // Original entry should be unchanged
        XCTAssertTrue(history.entries[0].isRunning)
    }

    func testDeleteEntryReturnsRemovedEntry() {
        var history = RunLogHistory()
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        let entryId = entry.id
        history.append(entry)

        let removed = history.deleteEntry(id: entryId)
        XCTAssertEqual(removed?.id, entryId)
        XCTAssertTrue(history.entries.isEmpty)
    }

    func testDeleteEntryReturnsNilForNonexistentId() {
        var history = RunLogHistory()
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        history.append(entry)

        let removed = history.deleteEntry(id: UUID())
        XCTAssertNil(removed)
        XCTAssertEqual(history.entries.count, 1)
    }

    func testDeleteOldEntriesKeepsSpecifiedCount() {
        var history = RunLogHistory()
        for idx in 0 ..< 8 {
            let entry = RunLogEntry(programName: "game.exe", logFileName: "log_\(idx).log")
            history.append(entry)
        }

        let removed = history.deleteOldEntries(keepLast: 3)
        XCTAssertEqual(removed.count, 5)
        XCTAssertEqual(history.entries.count, 3)
    }

    func testDeleteOldEntriesReturnsEmptyWhenUnderLimit() {
        var history = RunLogHistory()
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        history.append(entry)

        let removed = history.deleteOldEntries(keepLast: 5)
        XCTAssertTrue(removed.isEmpty)
        XCTAssertEqual(history.entries.count, 1)
    }

    func testLogFileURLsResolvesRelativePaths() {
        var history = RunLogHistory()
        let entry1 = RunLogEntry(programName: "game.exe", logFileName: "2025-01-01.log")
        let entry2 = RunLogEntry(programName: "game.exe", logFileName: "2025-01-02.log")
        history.append(entry1)
        history.append(entry2)

        let logsFolder = URL(filePath: "/tmp/logs")
        let urls = history.logFileURLs(in: logsFolder)

        XCTAssertEqual(urls.count, 2)
        XCTAssertTrue(urls[0].path().contains("2025-01-01.log"))
        XCTAssertTrue(urls[1].path().contains("2025-01-02.log"))
    }

    // MARK: - Codable Round-Trip Tests

    func testRunLogEntryCodableRoundTrip() throws {
        var entry = RunLogEntry(programName: "test.exe", logFileName: "2025-01-01T00:00:00Z.log")
        entry.endTime = entry.startTime.addingTimeInterval(300)
        entry.exitCode = 0
        entry.activeWineDebugPreset = "verbose"
        entry.hasWineDebugOutput = true

        let encoder = PropertyListEncoder()
        encoder.outputFormat = .xml
        let data = try encoder.encode(entry)
        let decoded = try PropertyListDecoder().decode(RunLogEntry.self, from: data)

        XCTAssertEqual(decoded.id, entry.id)
        XCTAssertEqual(decoded.programName, entry.programName)
        XCTAssertEqual(decoded.logFileName, entry.logFileName)
        XCTAssertEqual(decoded.exitCode, entry.exitCode)
        XCTAssertEqual(decoded.activeWineDebugPreset, entry.activeWineDebugPreset)
        XCTAssertEqual(decoded.hasWineDebugOutput, entry.hasWineDebugOutput)
        // Plist encoding rounds Date to whole seconds
        XCTAssertEqual(decoded.startTime.timeIntervalSince1970, entry.startTime.timeIntervalSince1970, accuracy: 1.0)
        let decodedEnd = try XCTUnwrap(decoded.endTime)
        let originalEnd = try XCTUnwrap(entry.endTime)
        XCTAssertEqual(decodedEnd.timeIntervalSince1970, originalEnd.timeIntervalSince1970, accuracy: 1.0)
    }

    func testRunLogHistoryCodableRoundTrip() throws {
        var history = RunLogHistory()
        for idx in 0 ..< 3 {
            var entry = RunLogEntry(programName: "game\(idx).exe", logFileName: "log_\(idx).log")
            entry.exitCode = Int32(idx)
            entry.endTime = entry.startTime.addingTimeInterval(Double(idx * 60))
            history.append(entry)
        }

        let encoder = PropertyListEncoder()
        encoder.outputFormat = .xml
        let data = try encoder.encode(history)
        let decoded = try PropertyListDecoder().decode(RunLogHistory.self, from: data)

        XCTAssertEqual(decoded.entries.count, history.entries.count)
        for (original, roundTripped) in zip(history.entries, decoded.entries) {
            XCTAssertEqual(roundTripped.id, original.id)
            XCTAssertEqual(roundTripped.programName, original.programName)
            XCTAssertEqual(roundTripped.logFileName, original.logFileName)
            XCTAssertEqual(roundTripped.exitCode, original.exitCode)
        }
    }

    // MARK: - RunLogStore Tests

    func testHistoryURLFormat() {
        let bottleURL = URL(filePath: "/tmp/bottle")
        let url = RunLogStore.historyURL(for: "game.exe", in: bottleURL)
        let urlPath = url.path(percentEncoded: false)
        XCTAssertTrue(urlPath.contains("Program Settings"), "Path should contain 'Program Settings': \(urlPath)")
        XCTAssertTrue(
            urlPath.contains("game.exe.run-history.plist"),
            "Path should contain 'game.exe.run-history.plist': \(urlPath)"
        )
    }

    func testLoadReturnsEmptyHistoryWhenFileDoesNotExist() {
        let history = RunLogStore.load(for: "nonexistent.exe", in: tempDir)
        XCTAssertTrue(history.entries.isEmpty)
    }

    func testSaveAndLoadRoundTrip() {
        var history = RunLogHistory()
        let entry = RunLogEntry(programName: "game.exe", logFileName: "test.log")
        history.append(entry)

        RunLogStore.save(history, for: "game.exe", in: tempDir)
        let loaded = RunLogStore.load(for: "game.exe", in: tempDir)

        XCTAssertEqual(loaded.entries.count, 1)
        XCTAssertEqual(loaded.entries[0].id, entry.id)
        XCTAssertEqual(loaded.entries[0].programName, "game.exe")
    }

    func testTotalLogSizeCalculation() throws {
        let logsDir = tempDir.appending(path: "logs")
        try FileManager.default.createDirectory(at: logsDir, withIntermediateDirectories: true)

        // Create some fake log files
        let data100 = Data(repeating: 0x41, count: 100)
        let data200 = Data(repeating: 0x42, count: 200)
        try data100.write(to: logsDir.appending(path: "run1.log"))
        try data200.write(to: logsDir.appending(path: "run2.log"))
        // Non-log file should be excluded
        try data100.write(to: logsDir.appending(path: "readme.txt"))

        let size = RunLogStore.totalLogSize(in: logsDir)
        XCTAssertEqual(size, 300)
    }

    func testTotalLogSizeReturnsZeroForNonexistentFolder() {
        let size = RunLogStore.totalLogSize(in: tempDir.appending(path: "nonexistent"))
        XCTAssertEqual(size, 0)
    }
}
