//
//  RuntimeManifest.swift
//  WhiskyKit
//
//  This file is part of Whisky.
//
//  Whisky is free software: you can redistribute it and/or modify it under the terms
//  of the GNU General Public License as published by the Free Software Foundation,
//  either version 3 of the License, or (at your option) any later version.
//
//  Whisky is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
//  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
//  See the GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with Whisky.
//  If not, see https://www.gnu.org/licenses/.
//

import Foundation

/// Hash manifest generated by the runtime producer and verified after extraction.
public struct RuntimeManifest: Codable, Equatable, Sendable {
    public struct File: Codable, Equatable, Sendable {
        public let path: String
        public let size: Int64
        public let sha256: String

        public init(path: String, size: Int64, sha256: String) {
            self.path = path
            self.size = size
            self.sha256 = sha256.lowercased()
        }
    }

    public let formatVersion: Int
    public let files: [File]

    public init(formatVersion: Int, files: [File]) {
        self.formatVersion = formatVersion
        self.files = files
    }
}

enum RuntimeManifestError: LocalizedError, Equatable {
    case unsupportedVersion(Int)
    case duplicatePath(String)
    case unsafePath(String)
    case missingFile(String)
    case undeclaredFile(String)
    case unexpectedFileType(String)
    case sizeMismatch(String)
    case digestMismatch(String)
    case malformed

    var errorDescription: String? {
        switch self {
        case let .unsupportedVersion(version):
            "Unsupported runtime manifest version: \(version)."
        case let .duplicatePath(path):
            "Runtime manifest contains the path more than once: \(path)."
        case let .unsafePath(path):
            "Runtime manifest contains an unsafe path: \(path)."
        case let .missingFile(path):
            "Runtime is missing a required file: \(path)."
        case let .undeclaredFile(path):
            "Runtime contains a file that is absent from its manifest: \(path)."
        case let .unexpectedFileType(path):
            "Runtime manifest entry is not a regular file: \(path)."
        case let .sizeMismatch(path):
            "Runtime file size does not match its manifest: \(path)."
        case let .digestMismatch(path):
            "Runtime file checksum does not match its manifest: \(path)."
        case .malformed:
            "The runtime manifest could not be decoded."
        }
    }
}

extension WhiskyWineInstaller {
    static let runtimeManifestName = "RuntimeManifest.json"

    /// Verifies a producer manifest when present. Legacy runtimes without one
    /// remain installable; metadata v2 runtimes must carry it.
    static func verifyRuntimeManifest(in libraryFolder: URL, info: WhiskyWineVersion) throws {
        let manifestURL = libraryFolder.appending(path: runtimeManifestName)
        let fileManager = FileManager.default
        let exists = fileManager.fileExists(atPath: manifestURL.path(percentEncoded: false))
        if !exists {
            if (info.manifestVersion ?? 1) >= 2 {
                throw RuntimeManifestError.missingFile(runtimeManifestName)
            }
            return
        }

        let manifest: RuntimeManifest
        do {
            manifest = try JSONDecoder().decode(RuntimeManifest.self, from: Data(contentsOf: manifestURL))
        } catch {
            throw RuntimeManifestError.malformed
        }
        guard manifest.formatVersion == 1 else {
            throw RuntimeManifestError.unsupportedVersion(manifest.formatVersion)
        }

        var seen = Set<String>()
        for entry in manifest.files {
            guard seen.insert(entry.path).inserted else {
                throw RuntimeManifestError.duplicatePath(entry.path)
            }
            guard isSafeManifestPath(entry.path) else {
                throw RuntimeManifestError.unsafePath(entry.path)
            }

            try verifyManifestEntry(entry, in: libraryFolder, fileManager: fileManager)
        }
        for required in ["Wine/bin/wine64", "Wine/bin/wineserver"] where !isRequiredBinaryPresent(
            required,
            in: libraryFolder,
            declared: seen,
            fileManager: fileManager
        ) {
            throw RuntimeManifestError.missingFile(required)
        }
        try rejectUndeclaredFiles(in: libraryFolder, declared: seen, fileManager: fileManager)
    }

    private static func isRequiredBinaryPresent(
        _ required: String,
        in libraryFolder: URL,
        declared: Set<String>,
        fileManager: FileManager
    ) -> Bool {
        if declared.contains(required) {
            return true
        }

        let file = libraryFolder.appending(path: required)
        let filePath = file.path(percentEncoded: false)
        guard fileManager.fileExists(atPath: filePath) else {
            return false
        }

        guard let attributes = try? fileManager.attributesOfItem(atPath: filePath),
              attributes[.type] as? FileAttributeType == .typeSymbolicLink else {
            return false
        }

        let canonicalLibrary = URL(fileURLWithPath: libraryFolder.path(percentEncoded: false))
            .resolvingSymlinksInPath()
            .standardizedFileURL
        let canonicalTarget = URL(fileURLWithPath: filePath)
            .resolvingSymlinksInPath()
            .standardizedFileURL

        let rootPrefix = canonicalLibrary.path + "/"
        guard canonicalTarget.path.hasPrefix(rootPrefix) else {
            return false
        }

        let relativePath = String(canonicalTarget.path.dropFirst(rootPrefix.count))
        return declared.contains(relativePath)
    }

    private static func verifyManifestEntry(
        _ entry: RuntimeManifest.File,
        in libraryFolder: URL,
        fileManager: FileManager
    ) throws {
        let file = libraryFolder.appending(path: entry.path)
        let attributes: [FileAttributeKey: Any]
        do {
            attributes = try fileManager.attributesOfItem(atPath: file.path(percentEncoded: false))
        } catch {
            throw RuntimeManifestError.missingFile(entry.path)
        }
        guard attributes[.type] as? FileAttributeType == .typeRegular else {
            throw RuntimeManifestError.unexpectedFileType(entry.path)
        }
        guard (attributes[.size] as? NSNumber)?.int64Value == entry.size else {
            throw RuntimeManifestError.sizeMismatch(entry.path)
        }
        guard let digest = sha256(ofFileAt: file), digest == entry.sha256.lowercased() else {
            throw RuntimeManifestError.digestMismatch(entry.path)
        }
    }

    private static func isSafeManifestPath(_ path: String) -> Bool {
        guard !path.isEmpty, !path.hasPrefix("/"), !path.contains("\0") else { return false }
        let components = path.split(separator: "/", omittingEmptySubsequences: false)
        return !components.contains(where: { $0.isEmpty || $0 == "." || $0 == ".." })
    }

    private static func rejectUndeclaredFiles(
        in libraryFolder: URL,
        declared: Set<String>,
        fileManager: FileManager
    ) throws {
        let root = libraryFolder.standardizedFileURL.path + "/"
        let metadata = Set(["WhiskyWineVersion.plist", runtimeManifestName])
        guard let enumerator = fileManager.enumerator(
            at: libraryFolder,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles]
        ) else { return }
        for case let file as URL in enumerator {
            guard try file.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile == true else { continue }
            let path = String(file.standardizedFileURL.path.dropFirst(root.count))
            guard !metadata.contains(path), !declared.contains(path) else { continue }
            throw RuntimeManifestError.undeclaredFile(path)
        }
    }
}
